version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - UPLOAD_DIR=/app/uploads
      - OUTPUT_DIR=/app/outputs
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    build: .
    command: celery -A main.celery worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379
      - UPLOAD_DIR=/app/uploads
      - OUTPUT_DIR=/app/outputs
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - redis
    restart: unless-stopped